seed_everything: 42
n_qubits: 8
qdim: 256
locality: 3
qencoder:
  class_path: pvqa.qencoder.ShadowBottomUpEncoder
  init_args:
    embedding: AmplitudeEmbedding
    embedding_kwargs:
      normalize: true
trainer:
  max_epochs: 50
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_f1_score
        mode: max
        every_n_epochs: 1
model:
  class_path: pvqa.model.SimpleClassifier
  init_args:
    labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
data:
  class_path: pvqa.datamodule.TorchVisionDataModule
  init_args:
    dataset_name: MNIST
    one_hot: true
    qnode_batch_size: 128
    train_batch_size: 128
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3