seed_everything: 42
n_qubits: 8
qdim: 256
kfold: 5
observables:
  class_path: pvqa.observables.LocalPauliObservables
  init_args:
    locality: 3
qencoder:
  class_path: pvqa.qencoder.TopDownEncoder
  init_args:
    embedding: AmplitudeEmbedding
    embedding_kwargs:
      normalize: true
    ansatz: StronglyEntanglingLayers
    derivative_order: 1
data:
  class_path: pvqa.datamodule.TorchVisionDataModule
  init_args:
    dataset_name: MNIST
    qnode_batch_size: 2
    train_batch_size: 32
    samples: 1000
    binary: true
model:
  class_path: pvqa.model.SimpleClassifier
  init_args:
    labels: 2
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-3
trainer:
  max_epochs: 50
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_f1_score
        mode: max
        every_n_epochs: 1